### PR TITLE
feat: support obsidian css snippets mode

### PR DESCRIPTION
**Pull request by zhaohongxuan**
add alternative way to use css snippet to use in exits Obsidian Vault
resolved issue: https://github.com/BingyanStudio/LapisCV/issues/4

### CODE REVIEW

**Comment by YiNNx** [comment]
Thanks! I will check it later

**Comment by YiNNx** [comment]
The PDF generated by this snippet seems to have some style differences compared to the original version (especially the page margin). Could it be adjusted to match the original?
image

**Comment by zhaohongxuan** [comment]
OK  I will check it later

**Comment by zhaohongxuan** [comment]
I adjust the quote and avatar style , but I can't tell the page margin between to version of resume:

image

**Comment by YiNNx** [comment]
Thanks for your work on this, but this feature is no longer under consideration (we still recommend using a single vault instead of relying on cssClass), so I’ll be closing this PR.

**Pull request closed without merging**
